const CATEGORY_COLORS = {
  Beef: "bg-red-600 text-white",
  Chicken: "bg-yellow-400 text-slate-900",
  Dessert: "bg-pink-400 text-white",
  Lamb: "bg-rose-700 text-white",
  Miscellaneous: "bg-slate-400 text-white",
  Pasta: "bg-orange-500 text-white",
  Pork: "bg-red-400 text-white",
  Seafood: "bg-sky-500 text-white",
  Side: "bg-emerald-400 text-white",
  Starter: "bg-lime-400 text-slate-900",
  Vegan: "bg-green-600 text-white",
  Vegetarian: "bg-green-400 text-slate-900",
  Breakfast: "bg-amber-400 text-slate-900",
  Goat: "bg-stone-600 text-white",
};

const AREA_COLORS = {
  Algerian: "bg-yellow-600 text-white",
  American: "bg-red-500 text-white",
  Argentinian: "bg-blue-400 text-white",
  Australian: "bg-green-500 text-white",
  British: "bg-indigo-600 text-white",
  Canadian: "bg-red-400 text-white",
  Chinese: "bg-red-700 text-white",
  Croatian: "bg-pink-500 text-white",
  Dutch: "bg-orange-400 text-white",
  Egyptian: "bg-yellow-500 text-slate-900",
  Filipino: "bg-rose-400 text-white",
  French: "bg-blue-600 text-white",
  Greek: "bg-cyan-500 text-white",
  Indian: "bg-amber-600 text-white",
  Irish: "bg-green-600 text-white",
  Italian: "bg-red-600 text-white",
  Jamaican: "bg-emerald-500 text-white",
  Japanese: "bg-red-300 text-slate-900",
  Kenyan: "bg-orange-500 text-white",
  Malaysian: "bg-indigo-500 text-white",
  Mexican: "bg-green-500 text-white",
  Moroccan: "bg-rose-600 text-white",
  Norwegian: "bg-blue-400 text-white",
  Polish: "bg-red-400 text-white",
  Portuguese: "bg-green-400 text-white",
  Russian: "bg-indigo-700 text-white",
  "Saudi Arabian": "bg-green-700 text-white",
  Slovakian: "bg-sky-500 text-white",
  Spanish: "bg-red-500 text-white",
  Syrian: "bg-amber-500 text-slate-900",
  Thai: "bg-pink-400 text-white",
  Tunisian: "bg-red-600 text-white",
  Turkish: "bg-red-400 text-white",
  Ukrainian: "bg-blue-300 text-slate-900",
  Uruguayan: "bg-cyan-400 text-slate-900",
  Venezulan: "bg-yellow-400 text-slate-900",
  Vietnamese: "bg-green-400 text-slate-900",
};

export { CATEGORY_COLORS, AREA_COLORS };
